server:
  port: 8080
  tomcat:
    threads:
      max: 10
      min-spare: 2
    accept-count: 5
    max-connections: 20

spring:
  application:
    name: OA System
  thymeleaf:
    cache: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:./oa.db
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
      connection-timeout: 5000
      idle-timeout: 600000
      max-lifetime: 1800000
  sql:
    init:
      mode: embedded
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.oa.entity
  configuration:
    map-underscore-to-camel-case: true
